Repository Welf06/Basic-Webpages, pull requests merged in 2022-10, with the labels that each got.

#5 Making changes to Contibution.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#6 Added updated README.md
  README.md
Labels: documentation, hacktoberfest-accepted

#14 all required changes done
  about.html
  index.html
  style3.css
  tools.html
Labels: hacktoberfest-accepted

#12 hacktoberfest-2022
  Calendar App/Intro
  Calendar App/img.jpg
  Calendar App/index.html
  Calendar App/style.css
  tools.html
Labels: hacktoberfest-accepted

#18 Added Countdown Timer for Launching pagesYasaswini999
  countDownTimer/index.html
  countDownTimer/main.js
  countDownTimer/style.css
  tools.html
Labels: hacktoberfest-accepted, hacktoberfest
